// Everyday American English — the wording US colleagues and clients actually use.
// Static data: browsing this costs nothing, no API calls.

export const PACKS = [
  {
    id: 'greetings',
    icon: 'coffee',
    title: 'Greetings & how to answer',
    blurb: 'Americans rarely say "How do you do". These are the real openers — and what to say back.',
    items: [
      { p: "How's it going?", m: 'The standard casual "how are you". Used with anyone, any time.', e: "Hey Mike, how's it going?", r: "Pretty good, thanks — how about you?" },
      { p: 'How are you doing today?', m: 'Slightly more formal; common at the start of a client call.', e: 'Good morning, Sarah. How are you doing today?', r: "I'm doing well, thanks for asking. And you?" },
      { p: "What's up?", m: 'Very casual, with colleagues you know. Often just a greeting, not a real question.', e: "Hey, what's up?", r: "Not much — you?" },
      { p: "How've you been?", m: 'For someone you haven\'t spoken to in a while.', e: "Long time! How've you been?", r: "Busy, but good. You?" },
      { p: 'Good to see you', m: 'Warm, works on video calls too ("Good to see you" beats "Nice to meet you" if you\'ve met before).', e: 'Hey Raj, good to see you again.', r: 'You too!' },
      { p: 'Morning!', m: 'Short for "good morning" — friendly and completely normal at work.', e: 'Morning, everyone.', r: 'Morning!' },
      { p: 'Hope you had a good weekend', m: 'Standard Monday opener before business.', e: 'Hi Tom — hope you had a good weekend.', r: 'I did, thanks. Quiet one. How about you?' },
    ],
  },
  {
    id: 'replies',
    icon: 'chat',
    title: 'Answering "How are you?"',
    blurb: 'Short, natural answers. Always bounce the question back.',
    items: [
      { p: "Pretty good, thanks — you?", m: 'The safest all-purpose answer.', e: "— How's it going? — Pretty good, thanks — you?" },
      { p: "Doing well, thanks", m: 'A touch more formal, good with clients.', e: "I'm doing well, thanks. How are things on your side?" },
      { p: "Can't complain", m: 'Relaxed and friendly; means "things are fine".', e: "— How've you been? — Can't complain!" },
      { p: 'Hanging in there', m: 'Honest "it\'s been a busy or tough week" — said lightly.', e: "— Busy week? — Hanging in there." },
      { p: 'Same old, same old', m: '"Nothing new" — casual, with people you know.', e: "— What's new? — Same old, same old." },
      { p: 'Busy, but good', m: 'Positive way to say you have a lot on.', e: 'Busy, but good — we just kicked off a new project.' },
      { p: 'All good here', m: 'Quick, upbeat, common on calls.', e: 'All good here — ready when you are.' },
    ],
  },
  {
    id: 'smalltalk',
    icon: 'users',
    title: 'Small talk that starts a call',
    blurb: 'US calls usually open with 30–60 seconds of this before business.',
    items: [
      { p: 'How was your weekend?', m: 'Monday and Tuesday standard.', e: 'Before we start — how was your weekend?' },
      { p: 'Any big plans for the weekend?', m: 'Thursday and Friday version.', e: 'Any big plans for the weekend?' },
      { p: 'How\'s the weather over there?', m: 'Safe topic across time zones.', e: "How's the weather over there? We're in the middle of the monsoon here." },
      { p: 'How\'s your week going so far?', m: 'Midweek opener.', e: "How's your week going so far?" },
      { p: 'Did you catch the game last night?', m: 'Sports small talk — only if you know they follow it.', e: 'Did you catch the game last night?' },
      { p: 'How are things on your end?', m: 'Moves small talk toward work.', e: 'How are things on your end?' },
      { p: 'Thanks for making the time', m: 'Polite opener when they moved their schedule for you.', e: 'Thanks for making the time today, I know it was short notice.' },
    ],
  },
  {
    id: 'calls',
    icon: 'phone',
    title: 'On the video call',
    blurb: 'The lines you need every single day on Zoom or Teams.',
    items: [
      { p: 'Can you hear me okay?', m: 'Standard audio check.', e: 'Can you hear me okay? My connection is a little shaky.' },
      { p: "You're on mute", m: 'Everyone says it, nobody minds.', e: 'Sarah — you\'re on mute.' },
      { p: 'Let me share my screen', m: 'Before presenting.', e: 'Let me share my screen and walk you through it.' },
      { p: 'Sorry, you cut out — could you say that again?', m: 'For a bad connection. Much better than "I did not get you".', e: 'Sorry, you cut out there — could you say that last part again?' },
      { p: "Let's give it a minute for folks to join", m: 'Waiting for latecomers.', e: "Let's give it a minute for folks to join." },
      { p: "I'll drop the link in the chat", m: 'Sharing something during the call.', e: "I'll drop the link in the chat for everyone." },
      { p: 'Go ahead', m: 'Invites someone to speak when you both started at once.', e: '— Sorry, go ahead. — No, please, go ahead.' },
      { p: 'I have a hard stop at 3', m: 'You must leave on time. Very common in US meetings.', e: 'Just a heads-up, I have a hard stop at 3.' },
    ],
  },
  {
    id: 'updates',
    icon: 'briefcase',
    title: 'Giving an update',
    blurb: 'How US teams phrase status, progress and problems.',
    items: [
      { p: "Here's where we're at", m: 'Opens a status update.', e: "Here's where we're at: two of the three feeds are live." },
      { p: "We're on track for Friday", m: 'Everything is going to plan.', e: "We're on track for Friday's delivery." },
      { p: 'We hit a snag', m: 'Something went wrong — softer than "there is an issue".', e: 'We hit a snag with the data load, but we have a workaround.' },
      { p: "I'm still waiting to hear back from…", m: 'Blocked by someone else, without blaming them.', e: "I'm still waiting to hear back from the vendor." },
      { p: "It's in progress", m: 'Started, not finished.', e: "The reconciliation is in progress — I'll have numbers by noon." },
      { p: 'Should be wrapped up by EOD', m: 'EOD = end of day. COB (close of business) is the same idea.', e: 'It should be wrapped up by EOD Thursday.' },
      { p: 'Quick heads-up —', m: 'Warns them about something before it becomes a problem.', e: 'Quick heads-up: the report may land an hour late tomorrow.' },
      { p: 'Let me look into it and get back to you', m: 'The US way of saying "I will revert".', e: "Good question — let me look into it and get back to you today." },
    ],
  },
  {
    id: 'agree',
    icon: 'check',
    title: 'Agreeing & disagreeing',
    blurb: 'Disagreement in US business English is soft on the outside, clear on the inside.',
    items: [
      { p: 'Totally', m: 'Strong, casual agreement.', e: '— We should test it first. — Totally.' },
      { p: 'That makes sense', m: 'Neutral agreement; shows you followed the logic.', e: 'That makes sense — let\'s go with that.' },
      { p: "I'm with you on that", m: 'Friendly, supportive agreement.', e: "I'm with you on that one." },
      { p: 'I see your point, but…', m: 'The standard polite disagreement opener.', e: 'I see your point, but the timeline worries me.' },
      { p: "I'd push back on that a little", m: 'Professional disagreement — direct but not rude.', e: "I'd push back on that a little — we tried it last quarter." },
      { p: 'Fair enough', m: 'Accepts their point without fully agreeing.', e: '— We need it by Tuesday. — Fair enough, we\'ll make it work.' },
      { p: 'Correct me if I\'m wrong, but…', m: 'Safest way to challenge something.', e: "Correct me if I'm wrong, but this was due last week." },
      { p: "Let's take that offline", m: 'Park a side discussion for later — very common in meetings.', e: "Good topic — let's take that offline and keep moving." },
    ],
  },
  {
    id: 'clarify',
    icon: 'alert',
    title: 'When you did not understand',
    blurb: 'Asking again is normal. These keep you sounding confident while you do it.',
    items: [
      { p: 'Sorry, could you say that again?', m: 'The default. Never say "come again" with a client.', e: 'Sorry, could you say that again? The audio dropped.' },
      { p: 'Just to make sure I\'ve got this right…', m: 'Confirms your understanding before acting.', e: "Just to make sure I've got this right — you want the file daily, not weekly?" },
      { p: 'What do you mean by…?', m: 'Asks about one specific word or term.', e: 'What do you mean by "refreshed"? Reloaded, or recalculated?' },
      { p: 'Could you walk me through that?', m: 'Asks for step by step detail.', e: 'Could you walk me through that process once more?' },
      { p: 'Let me repeat that back to you', m: 'Shows care on important instructions.', e: 'Let me repeat that back to you so we\'re aligned.' },
      { p: 'I have a question about…', m: 'Use this, not "I have a doubt" — "doubt" sounds like mistrust to Americans.', e: 'I have a question about the cut-off time.' },
      { p: 'Bear with me a second', m: 'Buys you a moment while you find something.', e: 'Bear with me a second while I pull up the file.' },
    ],
  },
  {
    id: 'soften',
    icon: 'sparkles',
    title: 'Softening what you say',
    blurb: 'Americans wrap requests and bad news in soft language. Direct commands sound harsh.',
    items: [
      { p: 'Would you mind…?', m: 'Polite request. "Kindly do the needful" sounds odd in the US.', e: 'Would you mind sending that over by noon?' },
      { p: 'Could you…?', m: 'Everyday request — friendlier than "Please do X".', e: 'Could you take a look when you get a chance?' },
      { p: 'When you get a chance', m: 'Signals "not urgent" and protects the relationship.', e: 'When you get a chance, could you approve the timesheet?' },
      { p: 'I might be wrong, but…', m: 'Lets you raise a concern without sounding combative.', e: "I might be wrong, but I think that number is from last month." },
      { p: 'It looks like…', m: 'Reports a problem gently.', e: 'It looks like a couple of trades are missing.' },
      { p: 'Would it make sense to…?', m: 'Proposes an idea as a question.', e: 'Would it make sense to run it twice a day instead?' },
      { p: 'Just a thought —', m: 'Offers a suggestion lightly.', e: 'Just a thought — we could automate that step.' },
      { p: 'No rush', m: 'Takes pressure off the other person.', e: "Whenever you get to it — no rush." },
    ],
  },
  {
    id: 'closing',
    icon: 'flag',
    title: 'Ending a call',
    blurb: 'US calls end quickly and warmly. Practise these until they are automatic.',
    items: [
      { p: "I'll let you go", m: 'The standard polite way to end, even if you called them.', e: "I know you have another meeting — I'll let you go." },
      { p: "Let's circle back next week", m: 'Return to the topic later.', e: "Let's circle back next week once the data is in." },
      { p: "I'll follow up with an email", m: 'Confirms in writing.', e: "I'll follow up with an email summarizing the actions." },
      { p: 'Thanks for your time', m: 'Client-safe closer.', e: 'Thanks for your time today, Sarah.' },
      { p: 'Sounds good — I\'ll take it from here', m: 'You are owning the next step.', e: "Sounds good — I'll take it from here and update you Thursday." },
      { p: 'Talk soon', m: 'Warm, informal sign-off.', e: 'Great catching up. Talk soon!' },
      { p: 'Have a good one', m: 'Very American "have a nice day".', e: 'Thanks again — have a good one!' },
    ],
  },
  {
    id: 'idioms',
    icon: 'book',
    title: 'Office idioms you will hear daily',
    blurb: 'If these go past you on a call, you lose the thread. Learn them first.',
    items: [
      { p: 'touch base', m: 'have a short catch-up', e: "Let's touch base Friday morning." },
      { p: 'circle back', m: 'return to a topic later', e: "I'll circle back once legal responds." },
      { p: 'loop in', m: 'add someone to the conversation', e: "Let me loop in Priya — she owns that feed." },
      { p: 'heads-up', m: 'advance warning', e: 'Thanks for the heads-up.' },
      { p: 'on the same page', m: 'in agreement / with the same understanding', e: 'Just want to make sure we\'re all on the same page.' },
      { p: 'ballpark', m: 'rough estimate', e: 'Can you give me a ballpark number?' },
      { p: 'run it by you', m: 'ask for your opinion or approval', e: 'I\'d like to run the deck by you first.' },
      { p: 'bandwidth', m: 'time and capacity to take work on', e: "I don't have the bandwidth this week." },
      { p: 'bring you up to speed', m: 'tell you what you missed', e: 'Let me bring you up to speed on the escalation.' },
      { p: 'drop the ball', m: 'fail to do something you were responsible for', e: 'We dropped the ball on that one — here\'s the fix.' },
      { p: 'wrap up', m: 'finish', e: "We should wrap up in five minutes." },
      { p: 'put a pin in it', m: 'pause a topic and come back to it', e: "Let's put a pin in that and move to the numbers." },
      { p: 'reach out', m: 'contact someone', e: "I'll reach out to the vendor today." },
      { p: 'nail down', m: 'settle the details firmly', e: 'Can we nail down the go-live date?' },
      { p: 'down the road', m: 'in the future', e: 'We can add the second region down the road.' },
      { p: 'on my plate', m: 'among the things I am handling', e: "I have a lot on my plate this week." },
    ],
  },
];

/** Wording that is normal in India but lands oddly with Americans. */
export const SWAPS = [
  { avoid: 'I will revert back to you', say: "I'll get back to you", note: '"Revert" means "go back to a previous state" in US English.' },
  { avoid: 'Please do the needful', say: 'Please take care of it / Could you handle this?', note: 'Americans do not use this phrase at all.' },
  { avoid: 'Kindly send the report', say: 'Could you send the report? / Please send the report', note: '"Kindly" sounds stiff and old-fashioned.' },
  { avoid: 'Can we prepone the meeting?', say: 'Can we move the meeting up? / move it earlier', note: '"Prepone" is not used in the US.' },
  { avoid: 'I have a doubt', say: 'I have a question', note: '"Doubt" suggests you distrust something.' },
  { avoid: 'He is out of station', say: "He's out of town / He's traveling", note: '' },
  { avoid: 'I passed out from college in 2014', say: 'I graduated in 2014', note: '"Passed out" means fainted.' },
  { avoid: 'May I know your good name?', say: 'May I have your name? / What\'s your name?', note: '"Good name" is not used.' },
  { avoid: 'Myself Sid', say: "I'm Sid / My name is Sid", note: '' },
  { avoid: 'Today morning / yesterday night', say: 'This morning / last night', note: '' },
  { avoid: "Let's discuss about the plan", say: "Let's discuss the plan", note: '"Discuss" takes no "about".' },
  { avoid: 'My cousin brother', say: 'My cousin', note: '' },
  { avoid: 'Please intimate me', say: 'Please let me know', note: '' },
  { avoid: 'Updation of the file', say: 'Updating the file / the update', note: '"Updation" is not an English word.' },
  { avoid: 'I am having 9 years of experience', say: 'I have nine years of experience', note: 'State facts with the simple present, not "am having".' },
  { avoid: 'Same to you', say: 'You too / Thanks, you too', note: 'Natural reply to "have a good weekend".' },
  { avoid: 'Do one thing…', say: 'Here\'s what I\'d suggest… / Why don\'t we…', note: '' },
  { avoid: 'It is there in the mail', say: "It's in the email", note: '' },
  { avoid: 'Reply back / return back', say: 'Reply / return', note: '"Back" is already in the meaning.' },
  { avoid: 'We are 5 members in the team', say: "There are five of us on the team", note: '' },
];

export const drillPrompt = (pack) => `(The learner wants to practise this set of everyday American English: "${pack.title}". Run a short, friendly drill in spoken English: put them in realistic little situations one at a time where they would naturally use these expressions — ${pack.items.slice(0, 6).map((i) => `"${i.p}"`).join(', ')} — and let them answer. React naturally, use the expressions yourself, and keep each turn under 40 words. Start with the first situation now.)`;
